# Facebook OAuth credentials
FACEBOOK_APP_ID=your_real_app_id
FACEBOOK_APP_SECRET=your_real_app_secret

# SMTP credentials
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=your-email@gmail.com
SMTP_PASSWORD=your-email-password

# OPEN AI credentials
OPEN_AI_API_KEY=your-open-ai-api-key

# Secret url segments
SECRET_URL_SEGMENT_DATABASE_STRUCTURE=c92k1Hnd9NOp0Wm3kSs9

# AWS (Amazon S3)
AWS_ACCESS_KEY=example
AWS_SECRET_KEY=example
AWS_S3_BUCKET_NAME=example
AWS_REGION=example

# Google OAuth
GOOGLE_OAUTH_TOKEN_INFO_URL=https://oauth2.googleapis.com/tokeninfo
OPEN_AI_API_URL=https://api.openai.com/v1/chat/completions